//
// auto-generated by op2.py
//

//user function
__device__ void EvolveValuesRK2_2_gpu( const float *dT,const float *Lw_1,
            const float *values,
            const float *w_1,
            float *out) {
  out[0] = 0.5*(Lw_1[0] * *dT + w_1[0] + values[0]);
  out[1] = 0.5*(Lw_1[1] * *dT + w_1[1] + values[1]);
  out[2] = 0.5*(Lw_1[2] * *dT + w_1[2] + values[2]);
  out[3] = values[3]-values[0];
  float TruncatedH = out[0] < EPS_cuda ? EPS_cuda : out[0];
  out[0] = TruncatedH;
  out[3] += TruncatedH;

}

// CUDA kernel function
__global__ void op_cuda_EvolveValuesRK2_2(
  const float *arg0,
  const float *__restrict arg1,
  const float *__restrict arg2,
  const float *__restrict arg3,
  float *arg4,
  int   set_size ) {


  //process set elements
  for ( int n=threadIdx.x+blockIdx.x*blockDim.x; n<set_size; n+=blockDim.x*gridDim.x ){

    //user-supplied kernel call
    EvolveValuesRK2_2_gpu(arg0,
                      arg1+n*4,
                      arg2+n*4,
                      arg3+n*4,
                      arg4+n*4);
  }
}


//host stub function
void op_par_loop_EvolveValuesRK2_2(char const *name, op_set set,
  op_arg arg0,
  op_arg arg1,
  op_arg arg2,
  op_arg arg3,
  op_arg arg4){

  float*arg0h = (float *)arg0.data;
  int nargs = 5;
  op_arg args[5];

  args[0] = arg0;
  args[1] = arg1;
  args[2] = arg2;
  args[3] = arg3;
  args[4] = arg4;

  // initialise timers
  double cpu_t1, cpu_t2, wall_t1, wall_t2;
  op_timing_realloc(1);
  op_timers_core(&cpu_t1, &wall_t1);
  OP_kernels[1].name      = name;
  OP_kernels[1].count    += 1;


  if (OP_diags>2) {
    printf(" kernel routine w/o indirection:  EvolveValuesRK2_2");
  }

  int set_size = op_mpi_halo_exchanges_grouped(set, nargs, args, 2);
  if (set_size > 0) {

    //transfer constants to GPU
    int consts_bytes = 0;
    consts_bytes += ROUND_UP(1*sizeof(float));
    reallocConstArrays(consts_bytes);
    consts_bytes = 0;
    arg0.data   = OP_consts_h + consts_bytes;
    arg0.data_d = OP_consts_d + consts_bytes;
    for ( int d=0; d<1; d++ ){
      ((float *)arg0.data)[d] = arg0h[d];
    }
    consts_bytes += ROUND_UP(1*sizeof(float));
    mvConstArraysToDevice(consts_bytes);

    //set CUDA execution parameters
    #ifdef OP_BLOCK_SIZE_1
      int nthread = OP_BLOCK_SIZE_1;
    #else
      int nthread = OP_block_size;
    #endif

    int nblocks = 200;

    op_cuda_EvolveValuesRK2_2<<<nblocks,nthread>>>(
      (float *) arg0.data_d,
      (float *) arg1.data_d,
      (float *) arg2.data_d,
      (float *) arg3.data_d,
      (float *) arg4.data_d,
      set->size );
  }
  op_mpi_set_dirtybit_cuda(nargs, args);
  if (OP_diags>1) {
    cutilSafeCall(cudaDeviceSynchronize());
  }
  //update kernel record
  op_timers_core(&cpu_t2, &wall_t2);
  OP_kernels[1].time     += wall_t2 - wall_t1;
  OP_kernels[1].transfer += (float)set->size * arg1.size;
  OP_kernels[1].transfer += (float)set->size * arg2.size;
  OP_kernels[1].transfer += (float)set->size * arg3.size;
  OP_kernels[1].transfer += (float)set->size * arg4.size * 2.0f;
}
