//
// auto-generated by op2.py
//

//user function
__device__ void EvolveValuesRK3_3_gpu( const float *dT, const float *values,
            const float *midPointConservative,
            float *Conservative,
            float *midPoint) {
  Conservative[0] = Conservative[0]/3.0f;
  Conservative[1] = Conservative[1]/3.0f;
  Conservative[2] = Conservative[2]/3.0f;

  Conservative[0] += ((2.0f * values[0])/3.0f) + ((*dT * midPointConservative[0])/6.0f);
  Conservative[1] += ((2.0f * (values[0]* values[1]))/3.0f) + (( *dT * midPointConservative[1])/6.0f);
  Conservative[2] += ((2.0f * (values[0]* values[2]))/3.0f) + (( *dT * midPointConservative[2])/6.0f);;
  Conservative[3] = Conservative[3];

  Conservative[0] = Conservative[0] <= EPS ? EPS : Conservative[0];

  float TruncatedH = Conservative[0] < EPS ? EPS : Conservative[0];
  midPoint[0] = Conservative[0];
  midPoint[1] = Conservative[1] / TruncatedH;
  midPoint[2] = Conservative[2] / TruncatedH;
  midPoint[3] = Conservative[3];
}

// CUDA kernel function
__global__ void op_cuda_EvolveValuesRK3_3(
  const float *arg0,
  const float *__restrict arg1,
  const float *__restrict arg2,
  float *arg3,
  float *arg4,
  int   set_size ) {


  //process set elements
  for ( int n=threadIdx.x+blockIdx.x*blockDim.x; n<set_size; n+=blockDim.x*gridDim.x ){

    //user-supplied kernel call
    EvolveValuesRK3_3_gpu(arg0,
                      arg1+n*4,
                      arg2+n*4,
                      arg3+n*4,
                      arg4+n*4);
  }
}


//host stub function
void op_par_loop_EvolveValuesRK3_3(char const *name, op_set set,
  op_arg arg0,
  op_arg arg1,
  op_arg arg2,
  op_arg arg3,
  op_arg arg4){

  float*arg0h = (float *)arg0.data;
  int nargs = 5;
  op_arg args[5];

  args[0] = arg0;
  args[1] = arg1;
  args[2] = arg2;
  args[3] = arg3;
  args[4] = arg4;

  // initialise timers
  double cpu_t1, cpu_t2, wall_t1, wall_t2;
  op_timing_realloc(2);
  op_timers_core(&cpu_t1, &wall_t1);
  OP_kernels[2].name      = name;
  OP_kernels[2].count    += 1;


  if (OP_diags>2) {
    printf(" kernel routine w/o indirection:  EvolveValuesRK3_3");
  }

  op_mpi_halo_exchanges_cuda(set, nargs, args);
  if (set->size > 0) {

    //transfer constants to GPU
    int consts_bytes = 0;
    consts_bytes += ROUND_UP(1*sizeof(float));
    reallocConstArrays(consts_bytes);
    consts_bytes = 0;
    arg0.data   = OP_consts_h + consts_bytes;
    arg0.data_d = OP_consts_d + consts_bytes;
    for ( int d=0; d<1; d++ ){
      ((float *)arg0.data)[d] = arg0h[d];
    }
    consts_bytes += ROUND_UP(1*sizeof(float));
    mvConstArraysToDevice(consts_bytes);

    //set CUDA execution parameters
    #ifdef OP_BLOCK_SIZE_2
      int nthread = OP_BLOCK_SIZE_2;
    #else
      int nthread = OP_block_size;
    //  int nthread = 128;
    #endif

    int nblocks = 200;

    op_cuda_EvolveValuesRK3_3<<<nblocks,nthread>>>(
      (float *) arg0.data_d,
      (float *) arg1.data_d,
      (float *) arg2.data_d,
      (float *) arg3.data_d,
      (float *) arg4.data_d,
      set->size );
  }
  op_mpi_set_dirtybit_cuda(nargs, args);
  cutilSafeCall(cudaDeviceSynchronize());
  //update kernel record
  op_timers_core(&cpu_t2, &wall_t2);
  OP_kernels[2].time     += wall_t2 - wall_t1;
  OP_kernels[2].transfer += (float)set->size * arg1.size;
  OP_kernels[2].transfer += (float)set->size * arg2.size;
  OP_kernels[2].transfer += (float)set->size * arg3.size * 2.0f;
  OP_kernels[2].transfer += (float)set->size * arg4.size * 2.0f;
}
