//
// auto-generated by op2.py
//

inline void NumericalFluxes(float *zeroInit)
{
  // float local = 0.0f;
  // local += *maxEdgeEigenvalues0 * *(EdgeVolumes0);
  // local += *maxEdgeEigenvalues1 * *(EdgeVolumes1);
  // local += *maxEdgeEigenvalues2 * *(EdgeVolumes2);
  zeroInit[0] = 0.0f;
  zeroInit[1] = 0.0f;
  zeroInit[2] = 0.0f;
  zeroInit[3] = 0.0f;

  // *minTimeStep = MIN(*minTimeStep, 2.0f * *cellVolumes / local);
}
