//
// auto-generated by op2.py
//

// header
#include "op_lib_cpp.h"
#define double_ALIGN 128
#define float_ALIGN 64
#define int_ALIGN 64
#ifdef VECTORIZE
#define SIMD_VEC 16
#define ALIGNED_double __attribute__((aligned(double_ALIGN)))
#define ALIGNED_float __attribute__((aligned(float_ALIGN)))
#define ALIGNED_int __attribute__((aligned(int_ALIGN)))
#else
#define ALIGNED_double
#define ALIGNED_float
#define ALIGNED_int
#endif

// global constants
extern float CFL;
extern float EPS;
extern float g;
// user kernel files
#include "EvolveValuesRK3_1_veckernel.cpp"
#include "EvolveValuesRK3_2_veckernel.cpp"
#include "EvolveValuesRK3_3_veckernel.cpp"
#include "EvolveValuesRK3_4_veckernel.cpp"
#include "simulation_1_veckernel.cpp"
#include "computeGradient_veckernel.cpp"
#include "limiter_veckernel.cpp"
#include "computeFluxes_veckernel.cpp"
#include "NumericalFluxes_veckernel.cpp"
#include "SpaceDiscretization_veckernel.cpp"
#include "getTotalVol_veckernel.cpp"
#include "getMaxElevation_veckernel.cpp"
#include "getMaxSpeed_veckernel.cpp"
#include "gatherLocations_veckernel.cpp"
#include "incConst_veckernel.cpp"
#include "initEta_formula_veckernel.cpp"
#include "initU_formula_veckernel.cpp"
#include "initV_formula_veckernel.cpp"
#include "values_operation2_veckernel.cpp"
#include "applyConst_veckernel.cpp"
#include "initBathymetry_large_veckernel.cpp"
#include "initBathyRelative_formula_veckernel.cpp"
#include "initBathymetry_formula_veckernel.cpp"
#include "initBathymetry_update_veckernel.cpp"
#include "initBore_select_veckernel.cpp"
#include "initGaussianLandslide_veckernel.cpp"
