//
// auto-generated by op2.py
//

// global constants
extern float CFL;
extern float EPS;
extern float g;

// header
#include "op_lib_cpp.h"

// user kernel files
#include "EvolveValuesRK3_1_kernel.cpp"
#include "EvolveValuesRK3_2_kernel.cpp"
#include "EvolveValuesRK3_3_kernel.cpp"
#include "EvolveValuesRK3_4_kernel.cpp"
#include "simulation_1_kernel.cpp"
#include "incConst_kernel.cpp"
#include "initEta_formula_kernel.cpp"
#include "initU_formula_kernel.cpp"
#include "initV_formula_kernel.cpp"
#include "values_operation2_kernel.cpp"
#include "applyConst_kernel.cpp"
#include "initBathymetry_large_kernel.cpp"
#include "initBathyRelative_formula_kernel.cpp"
#include "initBathymetry_formula_kernel.cpp"
#include "initBathymetry_update_kernel.cpp"
#include "initBore_select_kernel.cpp"
#include "initGaussianLandslide_kernel.cpp"
#include "getTotalVol_kernel.cpp"
#include "getMaxElevation_kernel.cpp"
#include "getMaxSpeed_kernel.cpp"
#include "gatherLocations_kernel.cpp"
#include "computeGradient_kernel.cpp"
#include "limiter_kernel.cpp"
#include "computeFluxes_kernel.cpp"
#include "NumericalFluxes_kernel.cpp"
#include "SpaceDiscretization_kernel.cpp"
